M48
; DRILL file {KiCad 7.0.9} date Thu Dec 19 19:35:33 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-12-19T19:35:33+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X1.8504Y-2.5984
X1.8504Y-5.2756
X6.3346Y-3.3465
X6.3346Y-4.5276
T0
M30
