M48
; DRILL file {KiCad 7.0.9} date Wed Jan 29 15:25:45 2025
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-01-29T15:25:45+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X2.9134Y-2.5984
X2.9134Y-5.2756
X7.3976Y-3.3465
X7.3976Y-4.5276
T0
M30
