M48
; DRILL file {KiCad 7.0.9} date Sat Aug 17 20:13:38 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-08-17T20:13:38+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0394
%
G90
G05
T1
X2.6Y-2.8
X2.7Y-2.8
X2.8Y-2.4
X2.8Y-2.8
X2.9Y-2.4
X2.9Y-2.8
T0
M30
