M48
; DRILL file {KiCad 7.0.9} date Tue Jun 25 21:06:51 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-06-25T21:06:51+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X2.6614Y-3.0945
X3.2913Y-4.7874
X4.7087Y-4.7874
X5.3386Y-3.0945
T0
M30
