M48
; DRILL file {KiCad 7.0.9} date Thu Dec 19 20:14:40 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-12-19T20:14:40+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.1496Y-2.1654
X3.1496Y-5.7087
X6.2992Y-2.3622
X6.2992Y-5.5118
T0
M30
