M48
; DRILL file {KiCad 7.0.9} date Tue May 14 12:43:38 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-14T12:43:38+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1378
%
G90
G05
T1
X1.9843Y-3.7402
X2.1811Y-5.9055
X4.5433Y-5.9055
X4.7402Y-3.7402
T0
M30
