M48
; DRILL file {KiCad 7.0.9} date Tue Dec 10 16:14:57 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-12-10T16:14:57+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.5669Y-3.622
X5.1969Y-5.315
X6.6142Y-5.315
X7.2441Y-3.622
T0
M30
