M48
; DRILL file {KiCad 7.0.9} date Tue Jun 25 19:44:48 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-06-25T19:44:48+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X6.9469Y-3.0969
X8.3219Y-5.6531
X9.5031Y-5.6531
X10.8781Y-3.0969
T0
M30
